env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules: {
  'no-empty': 0,
  camelcase: 0,
  indent: ['error', 'tab'],
  quotes: [2, 'single'],
  semi: [2, 'always'],
  no-tabs: 0,
  eqeqeq: 0
}
