CREATE TABLE user (
	USER_ID INTEGER NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	USER_PASSWORD TEXT NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	USER_DEACTIVATED BOOLEAN DEFAULT(FALSE)
);

CREATE TABLE device (
	USER_ID INTEGER NOT NULL,
	DEVICE_ID INTEGER NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	DEVICE_DEACTIVATED BOOLEAN DEFAULT(FALSE)
);

CREATE TABLE location (
	USER_ID INTEGER NOT NULL,
	DEVICE_ID INTEGER NOT NULL,
	LOCATION_ID INTEGER NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	LOCATION_LATITUDE NUMERIC NOT NULL,
	LOCATION_LONGITUDE NUMERIC NOT NULL
);
