CREATE TABLE user (
	USER_ID INTEGER NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	USER_DEACTIVATED BOOLEAN DEFAULT(FALSE)
);

CREATE TABLE user_auth (
	USER_ID INTEGER NOT NULL,
	USER_AUTH_ID INTEGER NOT NULL,
	USER_AUTH_PASSWORD TEXT NOT NULL,
	USER_AUTH_DEACTIVATED BOOLEAN DEFAULT(FALSE),
	CREATED_AT INTEGER NOT NULL
);

CREATE TABLE device (
	USER_ID INTEGER NOT NULL,
	DEVICE_ID INTEGER NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	DEVICE_DEACTIVATED BOOLEAN DEFAULT(FALSE)
);

CREATE TABLE device_auth (
	DEVICE_ID INTEGER NOT NULL,
	DEVICE_AUTH_ID INTEGER NOT NULL,
	DEVICE_AUTH_SECRET TEXT NOT NULL,
	DEVICE_AUTH_PUBLIC TEXT NOT NULL,
	DEVICE_AUTH_DEACTIVATED BOOLEAN DEFAULT(FALSE),
	CREATED_AT INTEGER NOT NULL
);

CREATE TABLE location (
	DEVICE_ID INTEGER NOT NULL,
	LOCATION_ID INTEGER NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	LOCATION_LATITUDE NUMERIC NOT NULL,
	LOCATION_LONGITUDE NUMERIC NOT NULL,
	LOCATION_ACCURACY NUMERIC NOT NULL,
	LOCATION_ALTITUDE NUMERIC,
	LOCATION_ALTITUDE_ACCURACY NUMERIC,
	LOCATION_HEADING NUMERIC,
	LOCATION_SPEED NUMERIC
);
